"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var FizzBuzz_1 = require("./FizzBuzz");
var fizzbuzz1 = new FizzBuzz_1.FizzBuzz(15);
var fizzbuzz2 = new FizzBuzz_1.FizzBuzz(10);
var fizzbuzz3 = new FizzBuzz_1.FizzBuzz(9);
var fizzbuzz4 = new FizzBuzz_1.FizzBuzz(11);
console.log(fizzbuzz1.message);
console.log(fizzbuzz2.message);
console.log(fizzbuzz3.message);
console.log(fizzbuzz4.message);
